# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.2.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/kanban-app: container
    io.kubernetes.cri-o.ContainerType/kanban-postgres: container
    io.kubernetes.cri-o.ContainerType/kanban-ui: container
    io.kubernetes.cri-o.SandboxID/kanban-app: edc2b58e6df788e4921acfcf3ea4a65d5438c48feacacd92773b6fb981eba58
    io.kubernetes.cri-o.SandboxID/kanban-postgres: edc2b58e6df788e4921acfcf3ea4a65d5438c48feacacd92773b6fb981eba58
    io.kubernetes.cri-o.SandboxID/kanban-ui: edc2b58e6df788e4921acfcf3ea4a65d5438c48feacacd92773b6fb981eba58
    io.kubernetes.cri-o.TTY/kanban-app: "true"
    io.kubernetes.cri-o.TTY/kanban-postgres: "true"
    io.kubernetes.cri-o.TTY/kanban-ui: "true"
    io.podman.annotations.autoremove/kanban-app: "FALSE"
    io.podman.annotations.autoremove/kanban-postgres: "FALSE"
    io.podman.annotations.autoremove/kanban-ui: "FALSE"
    io.podman.annotations.init/kanban-app: "FALSE"
    io.podman.annotations.init/kanban-postgres: "FALSE"
    io.podman.annotations.init/kanban-ui: "FALSE"
    io.podman.annotations.privileged/kanban-app: "FALSE"
    io.podman.annotations.privileged/kanban-postgres: "FALSE"
    io.podman.annotations.privileged/kanban-ui: "FALSE"
    io.podman.annotations.publish-all/kanban-app: "FALSE"
    io.podman.annotations.publish-all/kanban-postgres: "FALSE"
    io.podman.annotations.publish-all/kanban-ui: "FALSE"
    org.opencontainers.image.base.digest/kanban-app: sha256:51a4290ebef4d5cf1d96aa8eb140a02477d190281af6592e5bb919d5
    org.opencontainers.image.base.digest/kanban-ui: sha256:11432f1dae0d07e6cdd1e7540813b823fe7d5f37eaf9d8ea19599dcc
    org.opencontainers.image.base.name/kanban-app: docker.io/library/openjdk:8-alpine
    org.opencontainers.image.base.name/kanban-ui: docker.io/library/nginx:1.17.1-alpine
  creationTimestamp: "2022-10-20T17:40:47Z"
  labels:
    app: kanban-pod
  name: kanban-pod
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_USER
      value: kanban
    - name: POSTGRES_DB
      value: kanban
    - name: POSTGRES_PASSWORD
      value: kanban
    image: docker.io/library/postgres:9.6-alpine
    name: kanban-postgres
    ports:
    - containerPort: 80
      hostPort: 4200
    - containerPort: 5432
      hostPort: 5432
    - containerPort: 8080
      hostPort: 8080
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    tty: true
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: kanban-data-pvc
  - image: quay.io/slemeur/kanban-ui:latest
    name: kanban-ui
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    tty: true
  - env:
    - name: DB_SERVER
      value: kanban-postgres
    - name: POSTGRES_DB
      value: kanban
    - name: POSTGRES_USER
      value: kanban
    - name: POSTGRES_PASSWORD
      value: kanban
    image: quay.io/slemeur/kanban-app:latest
    name: kanban-app
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    tty: true
  hostname: kanban-pod
  restartPolicy: Never
  volumes:
  - name: kanban-data-pvc
    persistentVolumeClaim:
      claimName: kanban-data
status: {}
